# Site settings
title: NetSoc
email: social@netsoc.co.uk
description: Welcome to NetSoc!
baseurl: "/"
url: "netsoc.co.uk"

author:
  name     : 'Netsoc'
  email    : social@netsoc.co.uk
  url      : http://netsoc.co.uk
  facebook : https://www.facebook.com/groups/NetSocShu/
  twitter  : https://twitter.com/netsocshu
  slack    : https://netsocshu.slack.com

disqus_shortname: netsoc-co-uk
google_analytics: 

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
