# Site settings
title: NetSoc
email: social@netsoc.co.uk
description: Welcome to NetSoc!
baseurl: "/netsoc"
url: "https://netsocshu.github.io/netsoc"


author:
  name     : 'Netsoc'
  email    : social@netsoc.co.uk
  url      : http://netsoc.co.uk
  facebook : https://www.facebook.com/groups/NetSocShu/
  twitter  : https://twitter.com/netsocshu

disqus_shortname: 
google_analytics: 

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
